# Generated by Django 5.2.5 on 2025-08-23 07:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0003_rename_instruction_assignexercise_instruction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('total_duration', models.IntegerField(default=0)),
                ('videos_uploaded', models.IntegerField(default=0)),
                ('average_accuracy', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='Doctor.assignexercise')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='exercise_video/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('detected_exercise', models.CharField(blank=True, max_length=100, null=True)),
                ('detected_reps', models.IntegerField(default=0)),
                ('detected_sets', models.IntegerField(default=0)),
                ('accuracy_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('exercise_type', models.CharField(blank=True, max_length=50, null=True)),
                ('total_reps', models.IntegerField(default=0)),
                ('total_sets', models.IntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('frames_processed', models.IntegerField(default=0)),
                ('target_reps', models.IntegerField(default=0)),
                ('target_sets', models.IntegerField(default=0)),
                ('reps_accuracy', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('sets_accuracy', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('overall_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Doctor.assignexercise')),
            ],
        ),
    ]
