# Generated by Django 5.2.5 on 2025-08-19 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reps', models.IntegerField()),
                ('Sets', models.IntegerField()),
                ('Instruction', models.TextField(blank=True, null=True)),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('Exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.exercise')),
                ('Patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exercises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
