# Generated by Django 5.2.5 on 2025-08-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_assignexercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignexercise',
            old_name='Instruction',
            new_name='instruction',
        ),
        migrations.RenameField(
            model_name='assignexercise',
            old_name='Reps',
            new_name='reps',
        ),
        migrations.RenameField(
            model_name='assignexercise',
            old_name='Sets',
            new_name='sets',
        ),
    ]
